# Login page
fos_user_security_login:
    path: /login.html
    defaults: { _controller: UserBundle:Security:login }
    methods: [GET]

# Login page (POST)
fos_user_security_check:
    path: /login
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [POST]

# Logout
fos_user_security_logout:
    path: /logout
    defaults: { _controller: FOSUserBundle:Security:logout }
    methods: [GET]

# Register
fos_user_registration_register:
    path: /register/
    defaults: { _controller: UserBundle:Registration:register }
    methods: [GET, POST]

# Confirme register
fos_user_registration_confirmed:
    path: /register/confirmed
    defaults: { _controller: UserBundle:Registration:confirmed }

# Forgot password
fos_user_resetting_request:
    path: /login/password.html
    defaults: { _controller: UserBundle:Resetting:request }
    methods: [GET]

# Forgot password (POST)
fos_user_resetting_send_email:
    path: /login/password.html
    defaults: { _controller: UserBundle:Resetting:sendEmail }
    methods: [POST]

# Forgot password (link in mail)
fos_user_resetting_reset:
    path: /login/reset-password/{token}
    defaults: { _controller: UserBundle:Resetting:reset }
    methods: [GET, POST]

# Forgot : send mail
fos_user_resetting_check_email:
    path: /login/password-email
    defaults: { _controller: UserBundle:Resetting:checkEmail }
    methods: [GET]

fos_user_profile_show:
    path: /
