fos_user:
    db_driver: orm
    firewall_name: main
    user_class: UserBundle\Entity\User
    use_username_form_type: false
    from_email:
        address: "%mailer_sender_address%"
        sender_name: "%mailer_sender_name%"
    resetting:
        token_ttl: 7200
    registration:
        confirmation:
            enabled: true
