services:
    # Form : profil type
    profil.form.type:
        class: UserBundle\Form\Type\ProfilType
        arguments:
            - "%kernel.root_dir%"
        tags:
            - { name: form.type }
