services:
    # Homepage topic
    homepage.topic:
        class: AppBundle\Topic\HomeTopic
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name:  gos_web_socket.topic }
