services:
    # Online manager
    online.manager:
        class: AppBundle\Manager\OnlineManager
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
            - "@snc_redis.ws_client"

    # Event manager
    event.manager:
        class: AppBundle\Manager\EventManager

    # Homepage topic
    homepage.topic:
        class: AppBundle\Topic\HomeTopic
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@online.manager"
        tags:
            - { name:  gos_web_socket.topic }

    # Homepage listenr
    homepage.listener:
        class: AppBundle\EventListener\HomepageListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gos_web_socket.zmq.pusher"
        tags:
            - { name: kernel.event_subscriber }
