services:
    # Chat topic
    chat.topic:
        class: ChatBundle\Topic\ChatTopic
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@online.manager"
        tags:
            - { name: gos_web_socket.topic }

    # Chat RPC
    chat.rpc:
        class: ChatBundle\RPC\ChatRPC
        arguments:
            - "@gos_web_socket.websocket.client_manipulator"
            - "@doctrine.orm.entity_manager"
            - "@gos_web_socket.zmq.pusher"
            - "@event_dispatcher"
        tags:
            - { name: gos_web_socket.rpc }

    # Chat listener
    chat.listener:
        class: ChatBundle\EventListener\ChatListener
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@gos_web_socket.zmq.pusher"
            - "@translator"
        tags:
            - { name: kernel.event_subscriber }
